In [4]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def init_network():
    network={}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([[0.1, 0.2, 0.3]])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([[0.1, 0.2]])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([[0.1, 0.2]])
    return network
def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    return a3

network = init_network()
x=np.array([1.0,0.5])
y=forward(network,x)
print(y) #[0.31682708 0.69627909]

[[0.31682708 0.69627909]]


In [6]:
import numpy as np
import random  
network = init_network()
batch_size = 16
x=np.random.rand(1000,2)
for i in range(0,len(x),batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = forward(network,x_batch)
    print(y_batch)

[[0.31441683 0.6909137 ]
 [0.30948731 0.67997886]
 [0.31296429 0.68769993]
 [0.31483938 0.69185588]
 [0.3160264  0.69449626]
 [0.31823154 0.69939948]
 [0.31522393 0.69271634]
 [0.31410947 0.69022941]
 [0.3153292  0.69293638]
 [0.318443   0.699865  ]
 [0.31479292 0.69176067]
 [0.31863155 0.70028391]
 [0.31425459 0.69056022]
 [0.30971041 0.68047211]
 [0.31222054 0.68603729]
 [0.31524498 0.69275281]]
[[0.31367877 0.68928098]
 [0.31258113 0.68684822]
 [0.31491972 0.69203036]
 [0.31705908 0.69678266]
 [0.31454667 0.69121213]
 [0.316227   0.69493503]
 [0.31620212 0.6948756 ]
 [0.31556832 0.69348348]
 [0.31671745 0.69603385]
 [0.31719111 0.69707796]
 [0.30981119 0.6806965 ]
 [0.31465033 0.6914435 ]
 [0.31438017 0.69082338]
 [0.31490308 0.69198848]
 [0.31055957 0.68235298]
 [0.31747485 0.69771787]]
[[0.31462094 0.69135743]
 [0.31707532 0.69682656]
 [0.31339735 0.68866106]
 [0.31140423 0.68422507]
 [0.31700822 0.69666757]
 [0.3151486  0.69254233]
 [0.31282388 0.68738211]
 [0.31348149 0.68884959